line_endings = "Unix"  # Force Unix line endings
column_width = 80      # Set the maximum column width
indent_type = "Spaces" # Use spaces instead of tabs
indent_width = 2       # Set indent width to 2 spaces
