#!/usr/bin/env bash

CURRENTDIR="$(pwd)"
HOMEDIR="$HOME"

sync_vim() {
  for file in $(find nvim -name "*.lua" -o -name "*.vim"); do
    mkdir -p ~/.config/nvim/lua
    mkdir -p ~/.config/nvim/lua/olivia/core
    mkdir -p ~/.config/nvim/lua/olivia/plugins
    mkdir -p ~/.config/nvim/lua/olivia/plugins/lsp

    echo "Creating a symlink to $file in home directory"
    ln -sf "${CURRENTDIR}/${file}" "${HOMEDIR}/.config/${file}"
  done
}

sync_vim

unset sync_vim
