#!/usr/bin/env bash

CURRENTDIR="$(pwd)"
read -p "Enter home directory path (e.g.: /Users/myname): " HOMEDIR
echo "You've entered $HOMEDIR"
read -p "Continue? (Y/N): " confirm && [[ $confirm == [yY] || $confirm == [yY][eE][sS] ]] || exit 1

sync_vim() {
  for file in $(find nvim -name "*.lua" -o -name "*.vim"); do
    mkdir -p ~/.config/nvim/lua
    mkdir -p ~/.config/nvim/lua/user/lsp-config/settings

    echo "Creating a symlink to $file in home directory"
    ln -sf "${CURRENTDIR}/${file}" "${HOMEDIR}/.config/${file}"
  done
}

sync_vim

unset sync_vim
