require 'user.options'
require 'user.plugins'
require 'user.colorscheme'
require 'user.nvim-tree-config'
require 'user.mappings'
require 'user.lsp-config'
require 'user.statusline'
require 'user.treesitter'
